### PR TITLE
Remove explicit dependancy to jQuery

### PR DESCRIPTION
**Pull request by feychenie**
Sometimes Backbone is used without jQuery (see https://github.com/akre54/Backbone.NativeAjax)

### CODE REVIEW

**Comment by homeslicesolutions** [comment]
I'm going to test this first to see if multipart form would work with the Backbone Native

**Comment by homeslicesolutions** [comment]
i wanted to test if this works, but I'll take your word for it... lets see if anyone else has an issue

**Comment by HuFlungDu** [comment]
This merge causes the library to not work with jQuery > 1.5.1. Specifically, from that point on, `beforeSend` passes in a `jqXhr` object to it's callback, not an `XMLHttpRequest`, and the `jqXhr` object does not have an `upload` property. It may be necessary to run a check for `Backbone.$` and handle the binding differently depending on what you find.

**Comment by homeslicesolutions** [comment]
Hi,

I had a feeling this may happen. Can you make the change?  I will merge it back.

Joe

**Comment by HuFlungDu** [comment]
I'm working on a merge to allow the upload to take an array (since you can't create a FileList from an array of Files in JavaScript), which includes those changes. Just need to make the tests work and I'll make a pull request.

I'd like to add a way to handle both types, though. I'll look into that, first.

**Pull request merged**
